astra_camera:
  name: Astra Camera
  description: "This is a description"
  type: camera
  package_name: astra_camera
  node_name: astra_camera_node
  launch_file: astra_camera.launch
  enabled: false
  params:
    camera_name:
      type: string
      value: "camera"
      description: "Nom unique de la caméra utilisé comme espace de noms pour les topics et les services."
    depth_align:
      type: bool
      value: false
      description: "Active l'alignement matériel de la profondeur avec l'image couleur."
    serial_number:
      type: string
      value: ""
      description: "Numéro de série de la caméra pour identifier un périphérique spécifique."
    device_num:
      type: int
      value: 1
      description: "Numéro de l'appareil à utiliser lorsqu'il y a plusieurs caméras connectées."
      range: [0, 10]
    vendor_id:
      type: int
      value: 0
      description: "Identifiant du fournisseur USB pour filtrer les périphériques spécifiques."
      range: [0, 65535]
    product_id:
      type: int
      value: 0
      description: "Identifiant du produit USB pour filtrer les périphériques spécifiques."
      range: [0, 65535]
    enable_point_cloud:
      type: bool
      value: true
      description: "Active la publication du nuage de points 3D."
    enable_point_cloud_xyzrgb:
      type: bool
      value: false
      description: "Active la publication du nuage de points avec des données de couleur RGB."
    connection_delay:
      type: int
      value: 100
      description: "Délai en millisecondes avant d'établir la connexion avec la caméra."
      range: [0, 10000]
    color_width:
      type: int
      value: 640
      description: "Largeur de l'image couleur en pixels."
      range: [160, 1920]
    color_height:
      type: int
      value: 480
      description: "Hauteur de l'image couleur en pixels."
      range: [120, 1080]
    color_fps:
      type: int
      value: 30
      description: "Fréquence d'images par seconde pour le flux couleur."
      range: [1, 60]
    enable_color:
      type: bool
      value: true
      description: "Active le flux de la caméra couleur."
    flip_color:
      type: bool
      value: false
      description: "Active le retournement horizontal de l'image couleur."
    color_format:
      type: string
      value: "RGB"
      description: "Format de l'image couleur (par exemple, RGB, YUV)."
    depth_width:
      type: int
      value: 640
      description: "Largeur de l'image de profondeur en pixels."
      range: [160, 1280]
    depth_height:
      type: int
      value: 480
      description: "Hauteur de l'image de profondeur en pixels."
      range: [120, 1024]
    depth_fps:
      type: int
      value: 30
      description: "Fréquence d'images par seconde pour le flux de profondeur."
      range: [1, 60]
    enable_depth:
      type: bool
      value: true
      description: "Active le flux de la caméra de profondeur."
    flip_depth:
      type: bool
      value: false
      description: "Active le retournement horizontal de l'image de profondeur."
    depth_format:
      type: string
      value: "Y11"
      description: "Format de l'image de profondeur (par exemple, Y11, Z16)."
    ir_width:
      type: int
      value: 640
      description: "Largeur de l'image infrarouge en pixels."
      range: [160, 1280]
    ir_height:
      type: int
      value: 480
      description: "Hauteur de l'image infrarouge en pixels."
      range: [120, 1024]
    ir_fps:
      type: int
      value: 30
      description: "Fréquence d'images par seconde pour le flux infrarouge."
      range: [1, 60]
    enable_ir:
      type: bool
      value: true
      description: "Active le flux de la caméra infrarouge."
    flip_ir:
      type: bool
      value: false
      description: "Active le retournement horizontal de l'image infrarouge."
    ir_format:
      type: string
      value: "Y10"
      description: "Format de l'image infrarouge (par exemple, Y10, Y12)."
    publish_tf:
      type: bool
      value: true
      description: "Active la publication des transformations TF entre les différentes images de la caméra."
    tf_publish_rate:
      type: float
      value: 10.0
      description: "Fréquence de publication des transformations TF en Hz."
      range: [0.1, 100.0]
    ir_info_uri:
      type: string
      value: ""
      description: "URI du fichier de calibration pour la caméra infrarouge."
    color_info_uri:
      type: string
      value: ""
      description: "URI du fichier de calibration pour la caméra couleur."
    color_roi_x:
      type: int
      value: -1
      description: "Coordonnée X du coin supérieur gauche de la région d'intérêt (ROI) pour l'image couleur."
      range: [-1, 1920]
    color_roi_y:
      type: int
      value: -1
      description: "Coordonnée Y du coin supérieur gauche de la région d'intérêt (ROI) pour l'image couleur."
      range: [-1, 1080]
    color_roi_width:
      type: int
      value: -1
      description: "Largeur de la région d'intérêt (ROI) pour l'image couleur."
      range: [-1, 1920]
    color_roi_height:
      type: int
      value: -1
      description: "Hauteur de la région d'intérêt (ROI) pour l'image couleur."
      range: [-1, 1080]
    depth_roi_x:
      type: int
      value: -1
      description: "Coordonnée X du coin supérieur gauche de la région d'intérêt (ROI) pour l'image de profondeur."
      range: [-1, 1280]
    depth_roi_y:
      type: int
      value: -1
      description: "Coordonnée Y"

    depth_roi_width:
      type: int
      value: -1
      description: "Largeur de la région d'intérêt (ROI) sur l'image de profondeur. Mettre -1 pour désactiver."
      range: [-1, 1280]

    depth_roi_height:
      type: int
      value: -1
      description: "Hauteur de la région d'intérêt (ROI) sur l'image de profondeur. Mettre -1 pour désactiver."
      range: [-1, 1024]

    depth_scale:
      type: float
      value: 1.0
      description: "Facteur de mise à l'échelle pour les valeurs de profondeur. Utile pour calibrer en mètres."
      range: [0.001, 10.0]

    color_depth_synchronization:
      type: bool
      value: false
      description: "Synchronise les images couleur et profondeur pour une correspondance temporelle plus précise."

    use_uvc_camera:
      type: bool
      value: true
      description: "Utilise une caméra UVC (USB Video Class) pour le flux vidéo couleur."

    uvc_vendor_id:
      type: string
      value: "0x2bc5"
      description: "Identifiant du fournisseur USB (Vendor ID) de la caméra UVC."

    uvc_product_id:
      type: string
      value: "0x0501"
      description: "Identifiant du produit USB (Product ID) de la caméra UVC."

    uvc_retry_count:
      type: int
      value: 100
      description: "Nombre de tentatives pour se connecter à la caméra UVC avant abandon."
      range: [0, 1000]

    uvc_camera_format:
      type: string
      value: "mjpeg"
      description: "Format vidéo utilisé par la caméra UVC (par exemple: mjpeg, yuyv)."

    uvc_flip:
      type: bool
      value: false
      description: "Active le retournement horizontal de l'image issue de la caméra UVC."

    oni_log_level:
      type: string
      value: "verbose"
      description: "Niveau de log pour le pilote OpenNI (ex: none, error, warning, info, verbose)."

    oni_log_to_console:
      type: bool
      value: false
      description: "Active l'affichage des logs OpenNI dans la console."

    oni_log_to_file:
      type: bool
      value: false
      description: "Active l'enregistrement des logs OpenNI dans un fichier."

    enable_d2c_viewer:
      type: bool
      value: false
      description: "Active un visualiseur Depth-to-Color pour affichage local de l'image fusionnée."

    enable_publish_extrinsic:
      type: bool
      value: false
      description: "Active la publication des transformations extrinsèques entre capteurs."

    enable_keep_alive:
      type: bool
      value: false
      description: "Maintient la caméra active même en l'absence de souscripteurs aux topics."
